project:
  type: website

website:
  title: "Daniel's Data Stories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dpark2380/comm3180_S26_Blog
format:
  html:
    theme: darkly
    css: styles.css

execute:
  freeze: auto


